apiVersion: carto.run/v1alpha1
kind: ClusterImageTemplate
metadata:
  name: kpackimage
spec:
  imagePath: .status.latestImage
  template:
    apiVersion: kpack.io/v1alpha1
    kind: Image
    metadata:
      name: $(workload.metadata.name)$
    spec:
      tag: accordingtoali/$(workload.metadata.name)$
      serviceAccount: kpack-sa
      builder:
        kind: ClusterBuilder
        name: default
      source:
        blob:
          url: $(sources.source.url)$
