apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: gitops
  labels:
    app.tanzu.vmware.com/workload-type: deliver
spec:
  source:
    git:
      url: https://github.com/alinahid477/demo-app-deliverables.git
      ref:
        branch: main
